name: Publish to NuGet
on:
  push:
    branches:
      - master # Default release branch

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Specify the .NET 8 SDK version

      - name: Restore dependencies
        run: dotnet restore NativoPlusStudio.RequestResponsePattern/NativoPlusStudio.RequestResponsePattern.csproj

      - name: Build the project
        run: dotnet build --configuration Release NativoPlusStudio.RequestResponsePattern/NativoPlusStudio.RequestResponsePattern.csproj

      - name: Pack the project
        run: dotnet pack --configuration Release --output . NativoPlusStudio.RequestResponsePattern/NativoPlusStudio.RequestResponsePattern.csproj

      - name: Push to NuGet
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
